In [71]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('seaborn-whitegrid')
plt.rcParams['figure.dpi'] = 300

In [72]:
from sklearn.preprocessing import PolynomialFeatures

In [73]:
p_features = PolynomialFeatures(degree=2)

In [74]:
from sklearn.datasets import load_breast_cancer

In [75]:
data=load_breast_cancer()

In [76]:
df = pd.DataFrame( data['data'], columns=data['feature_names'])

In [77]:
df.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [67]:
target=data['target_names']
target


array(['malignant', 'benign'], dtype='<U9')

In [55]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
scale_model = StandardScaler()

In [56]:
scaled_features = scale_model.fit_transform(df)

In [57]:
scaled_features

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [58]:
scaled_features = pd.DataFrame(scaled_features, columns=df.columns)

In [59]:
scaled_features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   worst concave points  worst symmetry  worst fractal dimension  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

In [60]:
model=LogisticRegression()

In [64]:
from sklearn.model_selection import train_test_split

In [69]:
df.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [78]:
target = data['target']

In [80]:
target[:5]

array([0, 0, 0, 0, 0])

In [82]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features, target,test_size=0.2, )

In [83]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [84]:
pred=model.predict(X_test)

In [87]:
pred[:20]

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1])

In [88]:
model.score(X_test,y_test)

0.9912280701754386

In [104]:
X_test.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
278    -0.152598     -0.337343       -0.235980  -0.234892        -1.201293   
436    -0.357089      0.058258       -0.383029  -0.414355        -0.355847   
526    -0.189520     -0.125580       -0.186552  -0.295187         0.792763   
455    -0.212241      2.659920       -0.231861  -0.277838        -0.278277   
394    -0.575780     -0.365268       -0.572504  -0.593533         0.465402   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
278         -1.209502       -0.864150            -0.942490      -0.871183   
436         -0.483471       -0.889260            -0.722725       0.180289   
526          0.179262       -0.587439            -0.448793      -0.323542   
455         -0.570079       -0.760948            -0.419904      -1.594070   
394         -0.128131       -0.514369            -0.403912       0.457760   

     mean fractal dimension  ...  worst radius  worst texture  \
278               -1.077040  ...     -0.159286       0.068847   
436                0.095318  ...     -0.376722      -0.211245   
526                0.052790  ...     -0.190348      -0.084227   
455               -0.373909  ...     -0.252473       2.594554   
394               -0.168356  ...     -0.561026       0.019993   

     worst perimeter  worst area  worst smoothness  worst compactness  \
278        -0.248748   -0.248715         -1.199727          -1.132615   
436        -0.361040   -0.445953         -0.480818          -0.566578   
526        -0.159688   -0.282643          1.316453           0.369820   
455        -0.314872   -0.307605         -0.664929          -0.713526   
394        -0.563882   -0.564436          0.474804          -0.489605   

     worst concavity  worst concave points  worst symmetry  \
278        -0.797293             -0.955564       -0.915269   
436        -0.963911             -0.772997        0.666921   
526        -0.032568              0.427773        0.998566   
455        -0.969860             -0.563022       -1.140140   
394        -0.536788             -0.790964        0.239827   

     worst fractal dimension  
278                -1.181233  
436                -0.365513  
526                 0.149854  
455                -0.398762  
394                -0.727932  

[5 rows x 30 columns]