In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('seaborn-whitegrid')
plt.rcParams['figure.dpi'] = 300

In [20]:
from sklearn.datasets import load_wine
data=load_wine()

In [22]:
data['feature_names']

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [24]:
target=data['target']

In [25]:
df=pd.DataFrame(data['data'],columns=load_wine()['feature_names'])

In [26]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [28]:
target[:5]

array([0, 0, 0, 0, 0])

In [30]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
scale_model = StandardScaler()

In [31]:
model=LogisticRegression()

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df,target,test_size=0.2, )

In [36]:
X_train

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
140    12.93        2.81  2.70               21.0       96.0           1.54   
12     13.75        1.73  2.41               16.0       89.0           2.60   
22     13.71        1.86  2.36               16.6      101.0           2.61   
88     11.64        2.06  2.46               21.6       84.0           1.95   
79     12.70        3.87  2.40               23.0      101.0           2.83   
..       ...         ...   ...                ...        ...            ...   
92     12.69        1.53  2.26               20.7       80.0           1.38   
177    14.13        4.10  2.74               24.5       96.0           2.05   
145    13.16        3.57  2.15               21.0      102.0           1.50   
29     14.02        1.68  2.21               16.0       96.0           2.65   
142    13.52        3.17  2.72               23.5       97.0           1.55   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
140        0.50                  0.53             0.75             4.60  0.77   
12         2.76                  0.29             1.81             5.60  1.15   
22         2.88                  0.27             1.69             3.80  1.11   
88         1.69                  0.48             1.35             2.80  1.00   
79         2.55                  0.43             1.95             2.57  1.19   
..          ...                   ...              ...              ...   ...   
92         1.46                  0.58             1.62             3.05  0.96   
177        0.76                  0.56             1.35             9.20  0.61   
145        0.55                  0.43             1.30             4.00  0.60   
29         2.33                  0.26             1.98             4.70  1.04   
142        0.52                  0.50             0.55             4.35  0.89   

     od280/od315_of_diluted_wines  proline  
140                          2.31    600.0  
12                           2.90   1320.0  
22                           4.00   1035.0  
88                           2.75    680.0  
79                           3.13    463.0  
..                            ...      ...  
92                           2.06    495.0  
177                          1.60    560.0  
145                          1.68    830.0  
29                           3.59   1035.0  
142                          2.06    520.0  

[142 rows x 13 columns]

In [37]:
y_train

array([2, 0, 0, 1, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1,
       2, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 2, 2, 0, 0, 2, 0, 1,
       1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 0, 1, 2, 1, 0,
       0, 2, 0, 1, 1, 1, 0, 1, 2, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 0, 2, 0,
       2, 2, 2, 0, 0, 1, 1, 2, 0, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 1, 1, 2, 1, 2, 0, 2, 2, 1, 0, 2, 0, 1, 1, 2, 0,
       1, 1, 1, 2, 0, 1, 2, 2, 0, 2])

In [39]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
pred=model.predict(X_test)

In [41]:
pred

array([0, 1, 0, 2, 1, 2, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 1,
       2, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 1, 1, 2])

In [42]:
model.score(X_test,y_test)

0.9166666666666666

In [50]:
n=df[3:20]
model.predict(n)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
target[3:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])